;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/RuiDemo
DestinationPath=Content/Localization/RuiDemo
ManifestName=RuiDemo.manifest
ArchiveName=RuiDemo.archive
NativeCulture=en
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GatherTextFromSource
SearchDirectoryPaths=%LOCPROJECTROOT%Source/
SearchDirectoryPaths=%LOCPROJECTROOT%Plugins/ReactiveUI/Source/
ExcludePathFilters=Config/Localization/*
ExcludePathFilters=Source/RuiHostTests/*
ExcludePathFilters=Plugins/ReactiveUI/Source/ReactiveUIEditor/*
FileNameFilters=*.cpp
FileNameFilters=*.h
FileNameFilters=*.c
FileNameFilters=*.inl
FileNameFilters=*.ini

[GatherTextStep1]
CommandletClass=GenerateGatherManifest

[GatherTextStep2]
CommandletClass=GenerateGatherArchive
bPurgeOldEmptyEntries=true

[GatherTextStep3]
CommandletClass=GenerateTextLocalizationResource
ResourceName=RuiDemo.locres

