// AUTO-GENERATED aggregator - DO NOT EDIT. Regenerated by RUICompile; the
// compiled source-file SET stays constant, only these contents change (D-19).
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "CoreMinimal.h"
#include "RuiContext.h"
#include "RuiCoreElements.h"
#include "RuiSignal.h"
#include "RuiSlateElements.h"
#include "RuiStyle.h"

#define RUI_UETKX_DECL_PHASE
#include "../ChildrenProof/ChildHost.uetkx.inl"
#include "../ChildrenProof/ChildParent.uetkx.inl"
#include "../GrammarProof/MultiReturnProof.uetkx.inl"
#include "../CycleProof/CycleA.uetkx.inl"
#include "../CycleProof/CycleB.uetkx.inl"
#undef RUI_UETKX_DECL_PHASE
#include "../ChildrenProof/ChildHost.uetkx.inl"
#include "../ChildrenProof/ChildParent.uetkx.inl"
#include "../GrammarProof/MultiReturnProof.uetkx.inl"
#include "../CycleProof/CycleA.uetkx.inl"
#include "../CycleProof/CycleB.uetkx.inl"
