// AUTO-GENERATED by RUICompile — DO NOT EDIT. Source: ContextDemo.style.uetkx
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.


#if defined(RUI_UETKX_DECL_PHASE)
namespace ContextDemoStyle
{
	inline const FLinearColor CoolTheme{0.23f, 0.65f, 0.95f, 1.0f};
		inline const FLinearColor WarmTheme{0.95f, 0.4f, 0.35f, 1.0f};
		inline const FLinearColor PanelBackground{0.02f, 0.02f, 0.03f, 0.85f};
} // namespace ContextDemoStyle

#else
#endif
