// AUTO-GENERATED aggregator - DO NOT EDIT. Regenerated by RUICompile; the
// compiled source-file SET stays constant, only these contents change (D-19).
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "CoreMinimal.h"
#include "RuiContext.h"
#include "RuiCoreElements.h"
#include "RuiSignal.h"
#include "RuiSlateElements.h"
#include "RuiStyle.h"

#include "../Screens/ContextDemo.uetkx.inl"
#include "../Screens/CustomDraw.uetkx.inl"
#include "../Screens/HelloWorld.uetkx.inl"
#include "../Screens/KeyedDiff.uetkx.inl"
#include "../Screens/SignalCounter.uetkx.inl"
#include "../Screens/SimpleCounter.uetkx.inl"
#include "../Screens/SimpleTextField.uetkx.inl"
#include "../Screens/SimpleUseEffect.uetkx.inl"
#include "../Screens/StressTest.uetkx.inl"
#include "../Screens/StyledPanels.uetkx.inl"
#include "../Screens/TicTacToe.uetkx.inl"
