// AUTO-GENERATED aggregator - DO NOT EDIT. Regenerated by RUICompile; the
// compiled source-file SET stays constant, only these contents change (D-19).
// Copyright (c) 2026 Yaniv Kalfa. All Rights Reserved.

#include "CoreMinimal.h"
#include "RuiContext.h"
#include "RuiCoreElements.h"
#include "RuiSignal.h"
#include "RuiSlateElements.h"
#include "RuiStyle.h"
#include "RuiRouter.h"
#if __has_include("RuiAssetBrush.h")
#include "RuiAssetBrush.h"
#endif
#if __has_include("RuiFieldHooks.h")
#include "RuiFieldHooks.h"
#endif
#if __has_include("RuiUmgElement.h")
#include "RuiUmgElement.h"
#endif
#if __has_include("RuiSignalViewModel.h")
#include "RuiSignalViewModel.h"
#endif
#if __has_include("RuiHostWidget.h")
#include "RuiHostWidget.h"
#endif
#if __has_include("RuiWorldSubsystem.h")
#include "RuiWorldSubsystem.h"
#endif
#if __has_include("RuiActivation.h")
#include "RuiActivation.h"
#endif
#if __has_include("RuiActivatableScreen.h")
#include "RuiActivatableScreen.h"
#endif
#if __has_include("RuiMvvmViewModel.h")
#include "RuiMvvmViewModel.h"
#endif
#if __has_include("UObject/StrongObjectPtr.h")
#include "UObject/StrongObjectPtr.h"
#endif
#if __has_include("Engine/World.h")
#include "Engine/World.h"
#endif

#define RUI_UETKX_DECL_PHASE
#include "../Screens/AcceptanceLab/AcceptanceLab.hooks.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.style.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabCard/LabCard.uetkx.inl"
#include "../Screens/CommonUiDemo/components/ActivationProbe/ActivationProbe.uetkx.inl"
#include "../Screens/ContextDemo/components/DemoContextPanel/DemoContextPanel.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.style.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.uetkx.inl"
#include "../Screens/CustomDraw/CustomDraw.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomFace/DoomFace.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomHUD/DoomHUD.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMainMenu/DoomMainMenu.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMinimap/DoomMinimap.uetkx.inl"
#include "../Screens/DoomDemo/DoomGameScreen.uetkx.inl"
#include "../Screens/HelloWorld/HelloWorld.uetkx.inl"
#include "../Screens/InteropShowcase/components/ShowcaseProbe/ShowcaseProbe.uetkx.inl"
#include "../Screens/InteropShowcase/InteropShowcase.uetkx.inl"
#include "../Screens/KeyedDiff/KeyedDiff.uetkx.inl"
#include "../Screens/MvvmDemo/MvvmDemo.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterHome/RouterHome.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterUser/RouterUser.uetkx.inl"
#include "../Screens/RouterDemo/RouterDemo.uetkx.inl"
#include "../Screens/SignalCounter/components/SignalPanel/SignalPanel.uetkx.inl"
#include "../Screens/SignalCounter/SignalCounter.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.hooks.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.uetkx.inl"
#include "../Screens/SimpleTextField/SimpleTextField.uetkx.inl"
#include "../Screens/SimpleUseEffect/SimpleUseEffect.uetkx.inl"
#include "../Screens/StressTest/StressTest.uetkx.inl"
#include "../Screens/StyledPanels/StyledPanels.uetkx.inl"
#include "../Screens/TicTacToe/TicTacToe.uetkx.inl"
#include "../Screens/UmgHostDemo/components/UmgHostInner/UmgHostInner.uetkx.inl"
#include "../Screens/UmgHostDemo/UmgHostDemo.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.uetkx.inl"
#include "../Screens/CommonUiDemo/CommonUiDemo.uetkx.inl"
#include "../Screens/DoomDemo/DoomGame.uetkx.inl"
#undef RUI_UETKX_DECL_PHASE
#include "../Screens/AcceptanceLab/AcceptanceLab.hooks.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.style.uetkx.inl"
#include "../Screens/AcceptanceLab/components/LabCard/LabCard.uetkx.inl"
#include "../Screens/CommonUiDemo/components/ActivationProbe/ActivationProbe.uetkx.inl"
#include "../Screens/ContextDemo/components/DemoContextPanel/DemoContextPanel.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.style.uetkx.inl"
#include "../Screens/ContextDemo/ContextDemo.uetkx.inl"
#include "../Screens/CustomDraw/CustomDraw.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomFace/DoomFace.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomHUD/DoomHUD.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMainMenu/DoomMainMenu.uetkx.inl"
#include "../Screens/DoomDemo/components/DoomMinimap/DoomMinimap.uetkx.inl"
#include "../Screens/DoomDemo/DoomGameScreen.uetkx.inl"
#include "../Screens/HelloWorld/HelloWorld.uetkx.inl"
#include "../Screens/InteropShowcase/components/ShowcaseProbe/ShowcaseProbe.uetkx.inl"
#include "../Screens/InteropShowcase/InteropShowcase.uetkx.inl"
#include "../Screens/KeyedDiff/KeyedDiff.uetkx.inl"
#include "../Screens/MvvmDemo/MvvmDemo.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterHome/RouterHome.uetkx.inl"
#include "../Screens/RouterDemo/components/RouterUser/RouterUser.uetkx.inl"
#include "../Screens/RouterDemo/RouterDemo.uetkx.inl"
#include "../Screens/SignalCounter/components/SignalPanel/SignalPanel.uetkx.inl"
#include "../Screens/SignalCounter/SignalCounter.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.hooks.uetkx.inl"
#include "../Screens/SimpleCounter/SimpleCounter.uetkx.inl"
#include "../Screens/SimpleTextField/SimpleTextField.uetkx.inl"
#include "../Screens/SimpleUseEffect/SimpleUseEffect.uetkx.inl"
#include "../Screens/StressTest/StressTest.uetkx.inl"
#include "../Screens/StyledPanels/StyledPanels.uetkx.inl"
#include "../Screens/TicTacToe/TicTacToe.uetkx.inl"
#include "../Screens/UmgHostDemo/components/UmgHostInner/UmgHostInner.uetkx.inl"
#include "../Screens/UmgHostDemo/UmgHostDemo.uetkx.inl"
#include "../Screens/AcceptanceLab/AcceptanceLab.uetkx.inl"
#include "../Screens/CommonUiDemo/CommonUiDemo.uetkx.inl"
#include "../Screens/DoomDemo/DoomGame.uetkx.inl"
